// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cleanbrightcompany.Data;

#nullable disable

namespace cleanbrightcompany.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230211020617_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("cleanbrightcompany.Data.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManufacturerEmail")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("TEXT");

                    b.HasKey("ManufacturerID");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ManufacturerID = 1,
                            ManufacturerEmail = "Manufacturer1@gmail.com",
                            ManufacturerName = "Manufacturer 1"
                        },
                        new
                        {
                            ManufacturerID = 2,
                            ManufacturerEmail = "Manufacturer2@gmail.com",
                            ManufacturerName = "Manufacturer 2"
                        },
                        new
                        {
                            ManufacturerID = 3,
                            ManufacturerEmail = "Manufacturer3@gmail.com",
                            ManufacturerName = "Manufacturer 3"
                        },
                        new
                        {
                            ManufacturerID = 4,
                            ManufacturerEmail = "Manufacturer4@gmail.com",
                            ManufacturerName = "Manufacturer 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
