const API_BASE_URL_DEVELOPMENT = 'https://localhost:7080';

const ENDPOINTS = {
    GET_ALL_MANUFACTURERS: 'get-all-manufacturers',
    GET_MANUFACTURERS_BY_ID: 'get-manufacturer-by-id',
    ADD_MANUFACTURER: 'add-manufacturer',
    UPDATE_MANUFACTURER: 'update-manufacturer',
    DELETE_MANUFACTURER_BY_ID: 'delete-manufacturer'
};

const development = {
    API_URL_GET_ALL_MANUFACTURERS: API_BASE_URL_DEVELOPMENT+'/'+ENDPOINTS.GET_ALL_MANUFACTURERS,
    API_URL_GET_MANUFACTURERS_BY_ID: API_BASE_URL_DEVELOPMENT+'/'+ENDPOINTS.GET_MANUFACTURERS_BY_ID,
    API_URL_ADD_MANUFACTURER: API_BASE_URL_DEVELOPMENT+'/'+ENDPOINTS.ADD_MANUFACTURER,
    API_URL_UPDATE_MANUFACTURER: API_BASE_URL_DEVELOPMENT+'/'+ENDPOINTS.UPDATE_MANUFACTURER,
    API_URL_DELETE_MANUFACTURER_BY_ID: API_BASE_URL_DEVELOPMENT+'/'+ENDPOINTS.DELETE_MANUFACTURER_BY_ID
};

export default development;